import { and, eq, or } from "drizzle-orm";
import { sdk } from "@blush/auth";
import {
  applicationDocuments,
  applications,
  certificateScans,
  certificates,
  studentProfiles,
} from "@blush/db/schema";
import type { StorageAccessCheck, StorageAccessDecision } from "@blush/storage/proxy-route";
import { dbOrThrow } from "../dbOrThrow";
import { resolveAccess } from "./access";

// Marketing assets published on public site.
const PUBLIC_KEY = /(^|\/)media\/(product|gallery|brochure)\//;

// Admissions documents: transcripts, government IDs, passport photos.
const APPLICATION_KEY = /(^|\/)applications\//;

// Scanned copies of paper certificates issued by the school.
const CERTIFICATE_KEY = /(^|\/)certificates\//;

// Back-office reports generated by the app.
const REPORT_KEY = /(^|\/)reports\//;

export type StorageKeyClass = "public" | "application" | "certificate" | "report" | "internal";

// Sorts a key into what it is, kept pure so the classification can be tested without a database.
export function classifyStorageKey(key: string): StorageKeyClass {
  if (APPLICATION_KEY.test(key)) return "application";
  if (CERTIFICATE_KEY.test(key)) return "certificate";
  if (REPORT_KEY.test(key)) return "report";
  if (PUBLIC_KEY.test(key)) return "public";
  return "internal";
}

export const storageAccessPolicy: StorageAccessCheck = async (
  request,
  key,
): Promise<StorageAccessDecision> => {
  const kind = classifyStorageKey(key);
  if (kind === "public") return "allow";

  let user;
  try {
    user = await sdk.authenticateRequest(request);
  } catch {
    return "unauthenticated";
  }

  // Receipts, profile photos.
  if (kind === "internal") return "allow";

  const db = await dbOrThrow();
  const access = await resolveAccess(db, user);

  // A report is for the people who act on it.
  if (kind === "report") {
    return access.canAny("reports.read", "inventory.read") ? "allow" : "forbidden";
  }

  // A certificate scan is a back-office record, and the graduate's own document.
  if (kind === "certificate") {
    if (access.can("certificates.read")) return "allow";

    const [own] = await db
      .select({ id: certificateScans.id })
      .from(certificateScans)
      .innerJoin(certificates, eq(certificateScans.certificateId, certificates.id))
      .innerJoin(studentProfiles, eq(certificates.studentId, studentProfiles.id))
      .where(and(eq(certificateScans.storageKey, key), eq(studentProfiles.userId, user.id)))
      .limit(1);

    return own ? "allow" : "forbidden";
  }

  // Only admissions documents carry identity papers.
  if (access.can("admissions.read")) return "allow";

  // The applicant may see their own papers, whether the row is linked through the account.
  const [owned] = await db
    .select({ id: applicationDocuments.id })
    .from(applicationDocuments)
    .innerJoin(applications, eq(applicationDocuments.applicationId, applications.id))
    .leftJoin(studentProfiles, eq(studentProfiles.applicationId, applications.id))
    .where(
      and(
        eq(applicationDocuments.storageKey, key),
        or(eq(applications.userId, user.id), eq(studentProfiles.userId, user.id)),
      ),
    )
    .limit(1);

  return owned ? "allow" : "forbidden";
};
