import PublicShell from "@/components/PublicShell";
import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";
import { CheckCircle2, Clock3 } from "lucide-react";
import { FormEvent, useState } from "react";

export default function AppointmentsPage() {
  const { data: services = [] } = trpc.platform.content.clinicServices.useQuery();
  const book = trpc.platform.appointments.book.useMutation();
  const [notice, setNotice] = useState("");
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); try { const result = await book.mutateAsync({ serviceId: Number(data.get("serviceId")), customerName: String(data.get("customerName")), customerEmail: String(data.get("customerEmail")), customerPhone: String(data.get("customerPhone")), startsAt: new Date(String(data.get("startsAt"))), note: String(data.get("note") || "") || undefined }); setNotice(`Your clinic request ${result.reference} has been received. The academy will confirm the time shortly.`); event.currentTarget.reset(); } catch (error) { setNotice(error instanceof Error ? error.message : "The appointment request could not be sent."); } }
  return <PublicShell><main className="container py-16 sm:py-24"><div className="grid gap-12 lg:grid-cols-[.85fr_1.15fr]"><div><p className="eyebrow">Student clinic</p><h1 className="mt-5 font-serif text-5xl leading-none text-[#474057] sm:text-6xl">A little care, thoughtfully practised.</h1><p className="mt-6 max-w-md text-lg leading-8 text-[#716a7d]">Book a supervised student-clinic service. Requests are sent directly to the school’s operations workspace for confirmation and follow-up.</p><div className="mt-10 grid gap-4">{services.map(service => <article key={service.id} className="rounded-2xl border border-white bg-white/65 p-5"><div className="flex justify-between gap-4"><div><h2 className="font-serif text-2xl text-[#51465c]">{service.name}</h2><p className="mt-2 text-sm leading-6 text-[#766e7d]">{service.description}</p></div><p className="whitespace-nowrap font-serif text-lg text-[#67566d]">GHS {Number(service.price).toFixed(2)}</p></div><p className="mt-3 flex items-center gap-1.5 text-xs text-[#817788]"><Clock3 className="h-3.5 w-3.5" /> {service.durationMinutes} minutes</p></article>)}</div></div><section className="rounded-[2rem] border border-white bg-white/70 p-7 shadow-[0_18px_48px_rgba(86,70,102,.08)] sm:p-10"><p className="eyebrow">Request an appointment</p><h2 className="mt-3 font-serif text-3xl text-[#51465c]">Choose a quiet moment.</h2>{notice && <p className={`mt-5 rounded-2xl p-4 text-sm ${notice.startsWith("Your") ? "bg-[#eef6ef] text-[#496a56]" : "bg-[#fff0f4] text-[#a14d65]"}`}>{notice.startsWith("Your") && <CheckCircle2 className="mr-2 inline h-4 w-4" />}{notice}</p>}<form className="mt-8 grid gap-5" onSubmit={submit}><label className="field-label">Service<select required name="serviceId" className="soft-input"><option value="">Select a clinic service</option>{services.map(service => <option key={service.id} value={service.id}>{service.name}</option>)}</select></label><div className="grid gap-4 sm:grid-cols-2"><label className="field-label">Full name<input required name="customerName" className="soft-input" /></label><label className="field-label">Phone<input required name="customerPhone" className="soft-input" /></label></div><label className="field-label">Email<input required type="email" name="customerEmail" className="soft-input" /></label><label className="field-label">Preferred date and time<input required type="datetime-local" name="startsAt" className="soft-input" /></label><label className="field-label">A note for the clinic<textarea name="note" className="soft-input min-h-24" /></label><Button type="submit" disabled={book.isPending} className="rounded-full bg-[#5f5277] text-white hover:bg-[#4d4264]">{book.isPending ? "Sending request…" : "Request appointment"}</Button></form></section></div></main></PublicShell>;
}
