import DashboardLayout from "@/components/DashboardLayout";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";
import { FormEvent } from "react";

export default function StaffPage() {
  const utils = trpc.useUtils();
  const overview = trpc.platform.staff.overview.useQuery();
  const inventory = trpc.platform.staff.inventory.useQuery();
  const enrollments = trpc.platform.staff.enrollments.useQuery();
  const assessments = trpc.platform.staff.assessments.useQuery();
  const applications = trpc.platform.staff.applications.useQuery();
  const team = trpc.platform.staff.team.useQuery();
  const appointments = trpc.platform.staff.appointments.useQuery();
  const consume = trpc.platform.staff.consumeInventory.useMutation({ onSuccess: () => { utils.platform.staff.inventory.invalidate(); utils.platform.staff.overview.invalidate(); } });
  const adjust = trpc.platform.staff.adjustInventory.useMutation({ onSuccess: () => { utils.platform.staff.inventory.invalidate(); utils.platform.staff.overview.invalidate(); } });
  const attendance = trpc.platform.staff.recordAttendance.useMutation({ onSuccess: () => utils.platform.portal.mine.invalidate() });
  const result = trpc.platform.staff.recordResult.useMutation({ onSuccess: () => utils.platform.portal.mine.invalidate() });
  const reviewApplication = trpc.platform.staff.reviewApplication.useMutation({ onSuccess: () => utils.platform.staff.applications.invalidate() });
  const updateAppointment = trpc.platform.staff.updateAppointment.useMutation({ onSuccess: () => utils.platform.staff.appointments.invalidate() });
  async function submitConsume(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); await consume.mutateAsync({ inventoryItemId: Number(data.get("item")), quantity: Number(data.get("quantity")), note: String(data.get("note") || "") || undefined }); event.currentTarget.reset(); }
  async function submitAdjust(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); await adjust.mutateAsync({ inventoryItemId: Number(data.get("item")), movementType: data.get("movement") as "received" | "adjustment" | "damaged" | "return", quantityDelta: Number(data.get("delta")), note: String(data.get("note")) }); event.currentTarget.reset(); }
  async function submitAttendance(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); await attendance.mutateAsync({ enrollmentId: Number(data.get("enrollment")), classDate: new Date(String(data.get("date"))), status: data.get("status") as "present" | "late" | "absent" | "excused" }); event.currentTarget.reset(); }
  async function submitResult(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); const selected = enrollments.data?.find(item => item.enrollment.id === Number(data.get("studentEnrollment"))); if (!selected) return; await result.mutateAsync({ assessmentId: Number(data.get("assessment")), studentId: selected.enrollment.studentId, score: Number(data.get("score")), grade: String(data.get("grade") || "") || undefined, instructorComment: String(data.get("comment") || "") || undefined }); event.currentTarget.reset(); }
  const itemOptions = <>{inventory.data?.map(item => <option key={item.id} value={item.id}>{item.name} · {item.quantityOnHand} on hand</option>)}</>;
  return <DashboardLayout><div className="mx-auto max-w-6xl"><p className="eyebrow">Staff workspace</p><h1 className="mt-2 font-serif text-4xl text-[#4d4458]">Keep the studio moving with care.</h1><div className="mt-7 grid gap-4 sm:grid-cols-2"><div className="rounded-3xl bg-[#e8f1ed] p-6"><p className="text-xs uppercase tracking-[.15em] text-[#688072]">Low stock items</p><p className="mt-3 font-serif text-4xl text-[#4e6658]">{overview.data?.lowStock ?? "—"}</p></div><div className="rounded-3xl bg-[#eee7f1] p-6"><p className="text-xs uppercase tracking-[.15em] text-[#806b83]">Clinic requests</p><p className="mt-3 font-serif text-4xl text-[#5c4f65]">{overview.data?.pendingAppointments ?? "—"}</p></div></div>
    <div className="mt-7 grid gap-5 xl:grid-cols-2"><form onSubmit={submitConsume} className="rounded-3xl border border-white bg-white/70 p-6"><p className="eyebrow">Classroom supply use</p><h2 className="mt-2 font-serif text-2xl text-[#51465c]">Record consumption</h2><div className="mt-5 grid gap-3"><select required name="item" className="soft-input"><option value="">Choose an item</option>{itemOptions}</select><input required name="quantity" type="number" min="1" placeholder="Quantity used" className="soft-input" /><input name="note" placeholder="Class or practical session" className="soft-input" /></div><Button type="submit" disabled={consume.isPending} className="mt-5 rounded-full bg-[#5f5277] text-white">Record classroom use</Button></form><form onSubmit={submitAdjust} className="rounded-3xl bg-[#eee7f1] p-6"><p className="eyebrow">Stock movement</p><h2 className="mt-2 font-serif text-2xl text-[#51465c]">Receive or adjust stock</h2><div className="mt-5 grid gap-3"><select required name="item" className="soft-input"><option value="">Choose an item</option>{itemOptions}</select><select name="movement" className="soft-input"><option value="received">Stock received</option><option value="adjustment">Adjustment</option><option value="damaged">Damaged stock</option><option value="return">Return to stock</option></select><input required name="delta" type="number" placeholder="Quantity change (+/-)" className="soft-input" /><input required name="note" placeholder="Reason or receiving note" className="soft-input" /></div><Button type="submit" disabled={adjust.isPending} className="mt-5 rounded-full bg-[#7d657e] text-white">Save stock movement</Button></form></div>
    <div className="mt-7 grid gap-5 xl:grid-cols-2"><form onSubmit={submitAttendance} className="rounded-3xl bg-[#e8f1ed] p-6"><p className="eyebrow">Class register</p><h2 className="mt-2 font-serif text-2xl text-[#51465c]">Record attendance</h2><div className="mt-5 grid gap-3"><select required name="enrollment" className="soft-input"><option value="">Choose a student</option>{enrollments.data?.map(item => <option key={item.enrollment.id} value={item.enrollment.id}>{item.studentName} · {item.courseTitle}</option>)}</select><input required name="date" type="date" className="soft-input" /><select name="status" className="soft-input"><option value="present">Present</option><option value="late">Late</option><option value="absent">Absent</option><option value="excused">Excused</option></select></div><Button type="submit" disabled={attendance.isPending} className="mt-5 rounded-full bg-[#5f5277] text-white">Save attendance</Button></form><form onSubmit={submitResult} className="rounded-3xl border border-white bg-white/70 p-6"><p className="eyebrow">Learning progress</p><h2 className="mt-2 font-serif text-2xl text-[#51465c]">Enter assessment result</h2><div className="mt-5 grid gap-3"><select required name="studentEnrollment" className="soft-input"><option value="">Choose a student</option>{enrollments.data?.map(item => <option key={item.enrollment.id} value={item.enrollment.id}>{item.studentName} · {item.courseTitle}</option>)}</select><select required name="assessment" className="soft-input"><option value="">Choose an assessment</option>{assessments.data?.map(item => <option key={item.id} value={item.id}>{item.title} · total {item.totalScore}</option>)}</select><div className="grid gap-3 sm:grid-cols-2"><input required name="score" type="number" min="0" step="0.01" placeholder="Score" className="soft-input" /><input name="grade" placeholder="Grade" className="soft-input" /></div><input name="comment" placeholder="Instructor comment" className="soft-input" /></div><Button type="submit" disabled={result.isPending} className="mt-5 rounded-full bg-[#5f5277] text-white">Save result</Button></form></div>
    <div className="mt-7 grid gap-5 xl:grid-cols-2"><section className="rounded-3xl border border-white bg-white/70 p-6"><p className="eyebrow">Admissions assistance</p><h2 className="mt-2 font-serif text-2xl text-[#51465c]">Submitted applications</h2><div className="mt-5 grid gap-3">{applications.data?.map(({ application, courseTitle }) => <div key={application.id} className="flex items-center justify-between gap-3 rounded-2xl bg-[#faf8fb] p-4"><div><p className="text-sm font-semibold text-[#574d63]">{application.fullName}</p><p className="mt-1 text-xs text-[#82798a]">{courseTitle}</p></div><Button size="sm" variant="outline" onClick={() => reviewApplication.mutate({ applicationId: application.id, status: "under_review" })}>Review</Button></div>) || <p className="text-sm text-[#807889]">No submitted applications are awaiting attention.</p>}</div></section><section className="rounded-3xl border border-white bg-white/70 p-6"><p className="eyebrow">Student clinic</p><h2 className="mt-2 font-serif text-2xl text-[#51465c]">Appointment requests</h2><div className="mt-5 grid gap-3">{appointments.data?.map(({ appointment, serviceName }) => <div key={appointment.id} className="rounded-2xl bg-[#faf8fb] p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="font-semibold text-[#574d63]">{appointment.customerName} · {serviceName}</p><p className="mt-1 text-xs text-[#82798a]">{new Date(appointment.startsAt).toLocaleString()} · {appointment.customerPhone}</p></div><Badge className="bg-[#f0e7ef] text-[#765d78] hover:bg-[#f0e7ef]">{appointment.status.replaceAll("_", " ")}</Badge></div><div className="mt-3 flex flex-wrap gap-2"><select value={appointment.status} onChange={event => updateAppointment.mutate({ appointmentId: appointment.id, status: event.target.value as "requested" | "confirmed" | "completed" | "cancelled" | "no_show" })} className="rounded-full border border-[#6d5c78]/15 bg-white px-3 py-2 text-xs text-[#5b5367]"><option value="requested">Requested</option><option value="confirmed">Confirmed</option><option value="completed">Completed</option><option value="cancelled">Cancelled</option><option value="no_show">No show</option></select><select defaultValue="" onChange={event => event.target.value && updateAppointment.mutate({ appointmentId: appointment.id, status: appointment.status, assignedStaffUserId: Number(event.target.value) })} className="rounded-full border border-[#6d5c78]/15 bg-white px-3 py-2 text-xs text-[#5b5367]"><option value="">Assign staff member</option>{team.data?.filter(member => member.userId).map(member => <option key={member.id} value={member.userId!}>{member.fullName}</option>)}</select></div></div>) || <p className="text-sm text-[#807889]">No appointments requested.</p>}</div></section></div>
  </div></DashboardLayout>;
}
