"use client";

import { FormEvent } from "react";
import { Button } from "@blush/ui/components/ui/button";
import DashboardLayout from "@/components/DashboardLayout";
import { trpc } from "@/lib/trpc";

export default function AdminAcademicPage() {
  const utils = trpc.useUtils();
  const students = trpc.admin.students.useQuery();
  const courses = trpc.content.courses.useQuery();
  const createEnrollment = trpc.admin.createEnrollment.useMutation({ onSuccess: () => { utils.admin.students.invalidate(); utils.staff.enrollments.invalidate(); } });
  const createAssessment = trpc.admin.createAssessment.useMutation({ onSuccess: () => utils.staff.assessments.invalidate() });
  async function submitEnrollment(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); await createEnrollment.mutateAsync({ studentId: Number(data.get("studentId")), courseId: Number(data.get("courseId")), expectedCompletionDate: data.get("completion") ? new Date(String(data.get("completion"))) : undefined }); event.currentTarget.reset(); }
  async function submitAssessment(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); await createAssessment.mutateAsync({ courseId: Number(data.get("courseId")), title: String(data.get("title")), assessmentType: data.get("type") as "theory" | "practical" | "project" | "exam", totalScore: Number(data.get("totalScore")), dueDate: data.get("dueDate") ? new Date(String(data.get("dueDate"))) : undefined }); event.currentTarget.reset(); }
  return <DashboardLayout><div className="mx-auto max-w-6xl"><p className="eyebrow">Academic set-up</p><h1 className="mt-2 font-serif text-4xl font-bold text-[#4d4458]">Create the structure for learning.</h1><div className="mt-7 grid gap-5 xl:grid-cols-2"><form onSubmit={submitEnrollment} className="rounded-3xl bg-[#eee7f1] p-6"><p className="eyebrow">Student enrolment</p><h2 className="mt-2 font-serif text-2xl text-[#51465c]">Place a student in a programme</h2><div className="mt-5 grid gap-3"><select required name="studentId" className="soft-input"><option value="">Select student</option>{students.data?.map(({ student }) => <option key={student.id} value={student.id}>{student.fullName} · {student.studentNumber}</option>)}</select><select required name="courseId" className="soft-input"><option value="">Select programme</option>{courses.data?.map(course => <option key={course.id} value={course.id}>{course.title}</option>)}</select><label className="field-label">Expected completion<input name="completion" type="date" className="soft-input" /></label></div><Button type="submit" disabled={createEnrollment.isPending} className="mt-5 rounded-full bg-[#5f5277] text-white">Create enrolment</Button></form><form onSubmit={submitAssessment} className="rounded-3xl border border-white bg-white/70 p-6"><p className="eyebrow">Assessment set-up</p><h2 className="mt-2 font-serif text-2xl text-[#51465c]">Add an assessment</h2><div className="mt-5 grid gap-3"><select required name="courseId" className="soft-input"><option value="">Select programme</option>{courses.data?.map(course => <option key={course.id} value={course.id}>{course.title}</option>)}</select><input required name="title" placeholder="Assessment title" className="soft-input" /><div className="grid gap-3 sm:grid-cols-2"><select name="type" className="soft-input"><option value="theory">Theory</option><option value="practical">Practical</option><option value="project">Project</option><option value="exam">Exam</option></select><input required name="totalScore" type="number" min="1" placeholder="Total score" className="soft-input" /></div><label className="field-label">Due date<input name="dueDate" type="date" className="soft-input" /></label></div><Button type="submit" disabled={createAssessment.isPending} className="mt-5 rounded-full bg-[#5f5277] text-white">Create assessment</Button></form></div></div></DashboardLayout>;
}
