"use client";

import Link from "next/link";
import { AlertTriangle, ArrowUpRight, GraduationCap, Package, ReceiptText, UserRoundPlus } from "lucide-react";
import { Badge } from "@blush/ui/components/ui/badge";
import DashboardLayout from "@/components/DashboardLayout";
import { trpc } from "@/lib/trpc";

const metricCards = [
  { key: "students", label: "Active students", icon: GraduationCap, tone: "bg-[#ece7f4] text-[#64568d]" },
  { key: "newApplications", label: "New applications", icon: UserRoundPlus, tone: "bg-[#f4e8ee] text-[#8a6176]" },
  { key: "newOrders", label: "New orders", icon: ReceiptText, tone: "bg-[#e7f1ed] text-[#54786a]" },
  { key: "lowStock", label: "Low-stock items", icon: AlertTriangle, tone: "bg-[#f7eee1] text-[#8b6e38]" },
] as const;

export default function AdminPage() {
  const dashboard = trpc.admin.dashboard.useQuery();
  const finance = trpc.admin.financeSummary.useQuery();
  return <DashboardLayout><div className="mx-auto max-w-7xl space-y-7"><div className="flex flex-wrap items-end justify-between gap-5"><div><p className="eyebrow">Administration</p><h1 className="mt-2 font-serif text-4xl text-[#4d4458]">The school, at a glance.</h1><p className="mt-2 text-sm text-[#766e7f]">A single operational view of learning, sales, stock, and admissions.</p></div><Link href="/admissions" className="rounded-full bg-[#5f5277] px-5 py-3 text-sm font-semibold text-white shadow-[0_10px_20px_rgba(95,82,119,.18)]">Review admissions</Link></div>
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{metricCards.map(card => { const Icon = card.icon; return <article key={card.key} className="rounded-3xl border border-white bg-white/70 p-5 shadow-[0_12px_28px_rgba(86,70,102,.06)]"><div className="flex items-center justify-between"><span className={`grid h-10 w-10 place-items-center rounded-2xl ${card.tone}`}><Icon className="h-5 w-5" /></span><ArrowUpRight className="h-4 w-4 text-[#a198aa]" /></div><p className="mt-8 text-3xl font-semibold text-[#51465f]">{dashboard.data?.metrics[card.key] ?? "—"}</p><p className="mt-1 text-xs font-medium uppercase tracking-[.12em] text-[#877e8d]">{card.label}</p></article>; })}</div>
    <div className="grid gap-5 xl:grid-cols-[1.1fr_.9fr]"><section className="rounded-3xl border border-white bg-white/70 p-6"><div className="flex items-center justify-between"><div><p className="eyebrow">Financial pulse</p><h2 className="mt-2 font-serif text-2xl text-[#51465c]">Revenue & expenses</h2></div><Link href="/finance" className="text-xs font-semibold text-[#705a76]">Open finance</Link></div><div className="mt-7 grid grid-cols-2 gap-4 sm:grid-cols-4"><div><p className="text-xs text-[#82798a]">Income</p><p className="mt-1 font-serif text-2xl">GHS {finance.data?.income.toFixed(2) ?? "0.00"}</p></div><div><p className="text-xs text-[#82798a]">Expenses</p><p className="mt-1 font-serif text-2xl">GHS {finance.data?.outgoings.toFixed(2) ?? "0.00"}</p></div><div><p className="text-xs text-[#82798a]">Net</p><p className="mt-1 font-serif text-2xl">GHS {finance.data?.net.toFixed(2) ?? "0.00"}</p></div><div><p className="text-xs text-[#82798a]">Outstanding</p><p className="mt-1 font-serif text-2xl">GHS {finance.data?.outstandingFees.toFixed(2) ?? "0.00"}</p></div></div></section>
      <section className="rounded-3xl bg-[#ede6ef] p-6"><p className="eyebrow">Control centre</p><h2 className="mt-2 font-serif text-2xl text-[#51465c]">Move through the work.</h2><div className="mt-5 grid gap-2 text-sm">{[["Admissions","/admissions"],["Inventory","/inventory"],["Orders","/orders"],["Finance","/finance"],["Clinic bookings","/staff"]].map(([label,path]) => <Link key={path} href={path} className="flex items-center justify-between rounded-xl bg-white/60 px-4 py-3 text-[#5b5367] hover:bg-white">{label}<ArrowUpRight className="h-4 w-4" /></Link>)}</div></section></div>
    <div className="grid gap-5 xl:grid-cols-2"><section className="rounded-3xl border border-white bg-white/70 p-6"><div className="flex items-center justify-between"><h2 className="font-serif text-2xl text-[#51465c]">Recent applications</h2><Link href="/admissions" className="text-xs text-[#705a76]">View all</Link></div><div className="mt-5 grid gap-3">{dashboard.data?.recentApplications.length ? dashboard.data.recentApplications.map(item => <div key={item.reference} className="flex items-center justify-between gap-3 rounded-2xl bg-[#faf8fb] p-4"><div><p className="text-sm font-semibold text-[#554c62]">{item.fullName}</p><p className="mt-1 text-xs text-[#827889]">{item.courseTitle}</p></div><Badge className="bg-[#f0e7ef] text-[#795f78] hover:bg-[#f0e7ef]">{item.status.replaceAll("_", " ")}</Badge></div>) : <p className="text-sm text-[#817889]">No submitted applications yet.</p>}</div></section>
      <section className="rounded-3xl border border-white bg-white/70 p-6"><div className="flex items-center justify-between"><h2 className="font-serif text-2xl text-[#51465c]">Recent orders</h2><Link href="/orders" className="text-xs text-[#705a76]">View all</Link></div><div className="mt-5 grid gap-3">{dashboard.data?.recentOrders.length ? dashboard.data.recentOrders.map(order => <div key={order.id} className="flex items-center justify-between gap-3 rounded-2xl bg-[#faf8fb] p-4"><div><p className="text-sm font-semibold text-[#554c62]">{order.orderNumber}</p><p className="mt-1 text-xs text-[#827889]">{order.customerName} · GHS {order.total.toFixed(2)}</p></div><Badge className="bg-[#e7f1ed] text-[#54786a] hover:bg-[#e7f1ed]">{order.fulfillmentStatus}</Badge></div>) : <p className="text-sm text-[#817889]">No store orders yet.</p>}</div></section></div>
  </div></DashboardLayout>;
}
